---
networks:
  - name: private
    type: manual
    subnets:
    - range: 10.244.0.0/24
      gateway: 10.244.0.1

compilation:
  vm_type: default
  network: private
  reuse_compilation_vms: true
  workers: 2

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240