#!/bin/bash

set -ex

DOTFILES_USER=<%= p('user') %>
RUN_DIR=/var/vcap/sys/run/dotfiles
LOG_DIR=/var/vcap/sys/log/dotfiles

mkdir -p ${RUN_DIR} ${LOG_DIR}
chown -R ${DOTFILES_USER}:${DOTFILES_USER} ${RUN_DIR} ${LOG_DIR}
mkdir -p /home/${DOTFILES_USER}/.dotfiles
cp -r /var/vcap/packages/dotfiles/* /home/${DOTFILES_USER}/.dotfiles
chown -R ${DOTFILES_USER}:${DOTFILES_USER} /home/${DOTFILES_USER}/.dotfiles

chsh -s /bin/bash ${DOTFILES_USER}

cd $RUN_DIR
GAWK_PATH=/var/vcap/packages/gawk_4.0.1
GIT_PATH=/var/vcap/packages/git_1.9.1
VIM_PATH=/var/vcap/packages/vim_8
cat <<BASHRC >> /home/${DOTFILES_USER}/.bashrc
PATH=${GAWK_PATH}/bin:${GIT_PATH}/bin:${VIM_PATH}/bin:$PATH
BASHRC

su -c "PATH=${GAWK_PATH}/bin:${GIT_PATH}/bin:${VIM_PATH}/bin:$PATH /home/${DOTFILES_USER}/.dotfiles/bin/install.sh minimal" - $DOTFILES_USER
